[package]
name = "loro-rn"
version = "1.5.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
loro-ffi = "1.5.6"
uniffi = { version = "0.28.3" }

[build-dependencies]
uniffi = { version = "0.28.3", features = ["build", "cli"] }
